# Generated by Django 5.0.1 on 2024-01-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='askPrice',
            new_name='askprice',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='askQty',
            new_name='askqty',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='bidQty',
            new_name='bidqty',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='changeinOpenInterest',
            new_name='changeinopeninterest',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='expiryDate',
            new_name='expirydate',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='impliedVolatility',
            new_name='impliedvolatility',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='instrumentType',
            new_name='instrumenttype',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='lastPrice',
            new_name='lastprice',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='openInterest',
            new_name='openinterest',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='pChange',
            new_name='pchange',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='pchangeinOpenInterest',
            new_name='pchangeinopeninterest',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='strikePrice',
            new_name='strikeprice',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='totalBuyQuantity',
            new_name='totalbuyquantity',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='totalSellQuantity',
            new_name='totalsellquantity',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='totalTradedVolume',
            new_name='totaltradedvolume',
        ),
        migrations.RenameField(
            model_name='optiongreeks',
            old_name='underlyingValue',
            new_name='underlyingvalue',
        ),
    ]
