# Generated by Django 5.0.1 on 2024-01-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGreeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strikePrice', models.FloatField()),
                ('expiryDate', models.CharField(max_length=255)),
                ('underlying', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('openInterest', models.IntegerField()),
                ('changeinOpenInterest', models.IntegerField()),
                ('pchangeinOpenInterest', models.FloatField()),
                ('totalTradedVolume', models.IntegerField()),
                ('impliedVolatility', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('change', models.FloatField()),
                ('pChange', models.FloatField()),
                ('totalBuyQuantity', models.IntegerField()),
                ('totalSellQuantity', models.IntegerField()),
                ('bidQty', models.IntegerField()),
                ('bidprice', models.FloatField()),
                ('askQty', models.IntegerField()),
                ('askPrice', models.FloatField()),
                ('underlyingValue', models.FloatField()),
                ('instrumentType', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'option_greeks',
            },
        ),
    ]
