# Generated by Django 5.0.1 on 2024-01-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_askprice_optiongreeks_askprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongreeks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
